baseurl = "http://blog.kenjiskywalker.org"
title = "さよならインターネット"
languageCode = "ja-jp"
[params]
    bio = "さよならインターネット"
    name = "kenjiskywalker"
    description = "さよならインターネット"
    twitter = "kenjiskywalker"

[social]
    twitter  = "https://www.twitter.com/kenjiskywalker"
    github   = "https://www.github.com/kenjiskywalker"

#    [params.analytics]
#        googleid = "UA-37377904-1"

