baseurl = "http://blog.kenjiskywalker.org"
title = "さよならインターネット"
languageCode = "ja-jp"
[params]
    bio = "さよならインターネット"
    name = "kenjiskywalker"
    description = "さよならインターネット"
    twitter = "kenjiskywalker"
[permalinks]
    post = "/blog/:year/:month/:day/:title/"

[social]
    twitter  = "https://www.twitter.com/kenjiskywalker"
    github   = "https://www.github.com/kenjiskywalker"

# [params]
#   googleid = "UA-37377904-1"

